# Configuration for probot-stale - https://github.com/probot/stale

# Label to use when marking as stale
staleLabel: Stale
# Comment to post when removing the stale label. Set to `false` to disable
unmarkComment: false
# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 1

pulls:
  # Number of days of inactivity before a Pull Request becomes stale
  daysUntilStale: 30
  # Number of days of inactivity before a stale Pull Request is closed
  daysUntilClose: 7
  # Pull Requests with these labels will never be considered stale. Set to `[]` to disable
  exemptLabels:
    - Assigned
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This pull request has been automatically marked as stale because it has not had recent
    activity, and will be closed if no further activity occurs. If this pull request was
    overlooked, forgotten, or should remain open for any other reason, please reply
    here to call attention to it and remove the stale status. Thank you for your contributions.
  # Comment to post when closing a stale Pull Request. Set to `false` to disable
  closeComment: >
    This pull request has been automatically closed because it has not had
    recent activity. Please feel free to update or reopen it.
issues:
  # Number of days of inactivity before an Issue becomes stale
  daysUntilStale: 180
  # Number of days of inactivity before a stale Issue is closed
  daysUntilClose: 14
  # Issues with these labels will never be considered stale. Set to `[]` to disable
  exemptLabels: []
  # Comment to post when marking as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had activity
    in a long time. If this issue is still relevant and should remain open, please reply
    with a short explanation (e.g. "I have checked the code and this issue is still relevant because ___."
    or "Here's a screenshot of this issue on the latest version").
    Thank you for your contributions!
  # Comment to post when closing a stale Issue. Set to `false` to disable
  closeComment: >
    This issue has been automatically closed because it has not had
    activity in a long time. Please feel free to reopen it or create a new issue.
