# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.cache=true
org.gradle.cacheChecksumsEnabled=false
org.gradle.vfs.watch=true

JAVA_VERSION=25
MC_VERSION=26.1.2
MC_NEXT_VERSION=26.2
MCP_VERSION=20260409.101008
MAPPING_CHANNEL=official
MAPPING_VERSION=26.1.2

# Set to true before the first build of a new MC version, so we don't do compatibility checks
CHECK_COMPATIBILITY=false
# Set to true to allow for fuzzy patching. Useful during updateing
UPDATING=false
