# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.parallel=true

JAVA_VERSION=25
MC_VERSION=26.2
MC_NEXT_VERSION=26.3
MCP_VERSION=20260616.103818
MAPPING_CHANNEL=official
MAPPING_VERSION=26.2

# Set to true before the first build of a new MC version, so we don't do compatibility checks
CHECK_COMPATIBILITY=false
# Set to true to allow for fuzzy patching. Useful during updateing
UPDATING=false
