package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'MinecraftForge_MinecraftForge__Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("MinecraftForge_MinecraftForge__Build")) {
    features {
        add {
            commitStatusPublisher {
                id = "MinecraftForge_BuildWithNotifications_GithubStatusPublisher"
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:562c4bbc-e10e-454b-a6c7-b6a511443f01"
                    }
                }
            }
        }
    }
}
