package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.GitHubIssueTracker
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.githubIssues
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            password("env.CROWDIN_KEY", "credentialsJSON:dfdc0764-ae34-4ce2-972b-6e9ce730cbd2", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        update {
            password("env.CROWDIN_KEY", "credentialsJSON:a3102dbe-805d-4177-9f54-3d2c2eb08fd5", display = ParameterDisplay.HIDDEN)
        }
    }

    features {
        val feature1 = find<GitHubIssueTracker> {
            githubIssues {
                id = "MinecraftForge_MinecraftForge__IssueTracker"
                displayName = "MinecraftForge/MinecraftForge"
                repositoryURL = "https://github.com/MinecraftForge/MinecraftForge"
            }
        }
        feature1.apply {
        }
    }
}
