package net.minecraft.init;

import net.minecraft.block.Block;
import net.minecraft.block.BlockBeacon;
import net.minecraft.block.BlockBush;
import net.minecraft.block.BlockCauldron;
import net.minecraft.block.BlockChest;
import net.minecraft.block.BlockDaylightDetector;
import net.minecraft.block.BlockDeadBush;
import net.minecraft.block.BlockDoublePlant;
import net.minecraft.block.BlockFire;
import net.minecraft.block.BlockFlower;
import net.minecraft.block.BlockGrass;
import net.minecraft.block.BlockHopper;
import net.minecraft.block.BlockLeaves;
import net.minecraft.block.BlockLiquid;
import net.minecraft.block.BlockMycelium;
import net.minecraft.block.BlockPistonBase;
import net.minecraft.block.BlockPistonExtension;
import net.minecraft.block.BlockPistonMoving;
import net.minecraft.block.BlockPortal;
import net.minecraft.block.BlockRedstoneComparator;
import net.minecraft.block.BlockRedstoneRepeater;
import net.minecraft.block.BlockRedstoneWire;
import net.minecraft.block.BlockSlab;
import net.minecraft.block.BlockStainedGlass;
import net.minecraft.block.BlockStainedGlassPane;
import net.minecraft.block.BlockTallGrass;
import net.minecraft.block.BlockTripWireHook;

public class Blocks
{
    public static final Block air = (Block)Block.field_149771_c.getObject("air");
    public static final Block stone = (Block)Block.field_149771_c.getObject("stone");
    public static final BlockGrass grass = (BlockGrass)Block.field_149771_c.getObject("grass");
    public static final Block dirt = (Block)Block.field_149771_c.getObject("dirt");
    public static final Block cobblestone = (Block)Block.field_149771_c.getObject("cobblestone");
    public static final Block planks = (Block)Block.field_149771_c.getObject("planks");
    public static final Block sapling = (Block)Block.field_149771_c.getObject("sapling");
    public static final Block bedrock = (Block)Block.field_149771_c.getObject("bedrock");
    public static final BlockLiquid flowing_water = (BlockLiquid)Block.field_149771_c.getObject("flowing_water");
    public static final Block water = (Block)Block.field_149771_c.getObject("water");
    public static final BlockLiquid flowing_lava = (BlockLiquid)Block.field_149771_c.getObject("flowing_lava");
    public static final Block lava = (Block)Block.field_149771_c.getObject("lava");
    public static final Block sand = (Block)Block.field_149771_c.getObject("sand");
    public static final Block gravel = (Block)Block.field_149771_c.getObject("gravel");
    public static final Block gold_ore = (Block)Block.field_149771_c.getObject("gold_ore");
    public static final Block iron_ore = (Block)Block.field_149771_c.getObject("iron_ore");
    public static final Block coal_ore = (Block)Block.field_149771_c.getObject("coal_ore");
    public static final Block log = (Block)Block.field_149771_c.getObject("log");
    public static final Block log2 = (Block)Block.field_149771_c.getObject("log2");
    public static final BlockLeaves leaves = (BlockLeaves)Block.field_149771_c.getObject("leaves");
    public static final BlockLeaves leaves2 = (BlockLeaves)Block.field_149771_c.getObject("leaves2");
    public static final Block sponge = (Block)Block.field_149771_c.getObject("sponge");
    public static final Block glass = (Block)Block.field_149771_c.getObject("glass");
    public static final Block lapis_ore = (Block)Block.field_149771_c.getObject("lapis_ore");
    public static final Block lapis_block = (Block)Block.field_149771_c.getObject("lapis_block");
    public static final Block dispenser = (Block)Block.field_149771_c.getObject("dispenser");
    public static final Block sandstone = (Block)Block.field_149771_c.getObject("sandstone");
    public static final Block noteblock = (Block)Block.field_149771_c.getObject("noteblock");
    public static final Block bed = (Block)Block.field_149771_c.getObject("bed");
    public static final Block golden_rail = (Block)Block.field_149771_c.getObject("golden_rail");
    public static final Block detector_rail = (Block)Block.field_149771_c.getObject("detector_rail");
    public static final BlockPistonBase sticky_piston = (BlockPistonBase)Block.field_149771_c.getObject("sticky_piston");
    public static final Block web = (Block)Block.field_149771_c.getObject("web");
    public static final BlockTallGrass tallgrass = (BlockTallGrass)Block.field_149771_c.getObject("tallgrass");
    public static final BlockDeadBush deadbush = (BlockDeadBush)Block.field_149771_c.getObject("deadbush");
    public static final BlockPistonBase piston = (BlockPistonBase)Block.field_149771_c.getObject("piston");
    public static final BlockPistonExtension piston_head = (BlockPistonExtension)Block.field_149771_c.getObject("piston_head");
    public static final Block wool = (Block)Block.field_149771_c.getObject("wool");
    public static final BlockPistonMoving piston_extension = (BlockPistonMoving)Block.field_149771_c.getObject("piston_extension");
    public static final BlockFlower yellow_flower = (BlockFlower)Block.field_149771_c.getObject("yellow_flower");
    public static final BlockFlower red_flower = (BlockFlower)Block.field_149771_c.getObject("red_flower");
    public static final BlockBush brown_mushroom = (BlockBush)Block.field_149771_c.getObject("brown_mushroom");
    public static final BlockBush red_mushroom = (BlockBush)Block.field_149771_c.getObject("red_mushroom");
    public static final Block gold_block = (Block)Block.field_149771_c.getObject("gold_block");
    public static final Block iron_block = (Block)Block.field_149771_c.getObject("iron_block");
    public static final BlockSlab double_stone_slab = (BlockSlab)Block.field_149771_c.getObject("double_stone_slab");
    public static final BlockSlab stone_slab = (BlockSlab)Block.field_149771_c.getObject("stone_slab");
    public static final Block brick_block = (Block)Block.field_149771_c.getObject("brick_block");
    public static final Block tnt = (Block)Block.field_149771_c.getObject("tnt");
    public static final Block bookshelf = (Block)Block.field_149771_c.getObject("bookshelf");
    public static final Block mossy_cobblestone = (Block)Block.field_149771_c.getObject("mossy_cobblestone");
    public static final Block obsidian = (Block)Block.field_149771_c.getObject("obsidian");
    public static final Block torch = (Block)Block.field_149771_c.getObject("torch");
    public static final BlockFire fire = (BlockFire)Block.field_149771_c.getObject("fire");
    public static final Block mob_spawner = (Block)Block.field_149771_c.getObject("mob_spawner");
    public static final Block oak_stairs = (Block)Block.field_149771_c.getObject("oak_stairs");
    public static final BlockChest chest = (BlockChest)Block.field_149771_c.getObject("chest");
    public static final BlockRedstoneWire redstone_wire = (BlockRedstoneWire)Block.field_149771_c.getObject("redstone_wire");
    public static final Block diamond_ore = (Block)Block.field_149771_c.getObject("diamond_ore");
    public static final Block diamond_block = (Block)Block.field_149771_c.getObject("diamond_block");
    public static final Block crafting_table = (Block)Block.field_149771_c.getObject("crafting_table");
    public static final Block wheat = (Block)Block.field_149771_c.getObject("wheat");
    public static final Block farmland = (Block)Block.field_149771_c.getObject("farmland");
    public static final Block furnace = (Block)Block.field_149771_c.getObject("furnace");
    public static final Block lit_furnace = (Block)Block.field_149771_c.getObject("lit_furnace");
    public static final Block standing_sign = (Block)Block.field_149771_c.getObject("standing_sign");
    public static final Block wooden_door = (Block)Block.field_149771_c.getObject("wooden_door");
    public static final Block ladder = (Block)Block.field_149771_c.getObject("ladder");
    public static final Block rail = (Block)Block.field_149771_c.getObject("rail");
    public static final Block stone_stairs = (Block)Block.field_149771_c.getObject("stone_stairs");
    public static final Block wall_sign = (Block)Block.field_149771_c.getObject("wall_sign");
    public static final Block lever = (Block)Block.field_149771_c.getObject("lever");
    public static final Block stone_pressure_plate = (Block)Block.field_149771_c.getObject("stone_pressure_plate");
    public static final Block iron_door = (Block)Block.field_149771_c.getObject("iron_door");
    public static final Block wooden_pressure_plate = (Block)Block.field_149771_c.getObject("wooden_pressure_plate");
    public static final Block redstone_ore = (Block)Block.field_149771_c.getObject("redstone_ore");
    public static final Block lit_redstone_ore = (Block)Block.field_149771_c.getObject("lit_redstone_ore");
    public static final Block unlit_redstone_torch = (Block)Block.field_149771_c.getObject("unlit_redstone_torch");
    public static final Block redstone_torch = (Block)Block.field_149771_c.getObject("redstone_torch");
    public static final Block stone_button = (Block)Block.field_149771_c.getObject("stone_button");
    public static final Block snow_layer = (Block)Block.field_149771_c.getObject("snow_layer");
    public static final Block ice = (Block)Block.field_149771_c.getObject("ice");
    public static final Block snow = (Block)Block.field_149771_c.getObject("snow");
    public static final Block cactus = (Block)Block.field_149771_c.getObject("cactus");
    public static final Block clay = (Block)Block.field_149771_c.getObject("clay");
    public static final Block reeds = (Block)Block.field_149771_c.getObject("reeds");
    public static final Block jukebox = (Block)Block.field_149771_c.getObject("jukebox");
    public static final Block fence = (Block)Block.field_149771_c.getObject("fence");
    public static final Block pumpkin = (Block)Block.field_149771_c.getObject("pumpkin");
    public static final Block netherrack = (Block)Block.field_149771_c.getObject("netherrack");
    public static final Block soul_sand = (Block)Block.field_149771_c.getObject("soul_sand");
    public static final Block glowstone = (Block)Block.field_149771_c.getObject("glowstone");
    public static final BlockPortal portal = (BlockPortal)Block.field_149771_c.getObject("portal");
    public static final Block lit_pumpkin = (Block)Block.field_149771_c.getObject("lit_pumpkin");
    public static final Block cake = (Block)Block.field_149771_c.getObject("cake");
    public static final BlockRedstoneRepeater unpowered_repeater = (BlockRedstoneRepeater)Block.field_149771_c.getObject("unpowered_repeater");
    public static final BlockRedstoneRepeater powered_repeater = (BlockRedstoneRepeater)Block.field_149771_c.getObject("powered_repeater");
    public static final Block trapdoor = (Block)Block.field_149771_c.getObject("trapdoor");
    public static final Block monster_egg = (Block)Block.field_149771_c.getObject("monster_egg");
    public static final Block stonebrick = (Block)Block.field_149771_c.getObject("stonebrick");
    public static final Block brown_mushroom_block = (Block)Block.field_149771_c.getObject("brown_mushroom_block");
    public static final Block red_mushroom_block = (Block)Block.field_149771_c.getObject("red_mushroom_block");
    public static final Block iron_bars = (Block)Block.field_149771_c.getObject("iron_bars");
    public static final Block glass_pane = (Block)Block.field_149771_c.getObject("glass_pane");
    public static final Block melon_block = (Block)Block.field_149771_c.getObject("melon_block");
    public static final Block pumpkin_stem = (Block)Block.field_149771_c.getObject("pumpkin_stem");
    public static final Block melon_stem = (Block)Block.field_149771_c.getObject("melon_stem");
    public static final Block vine = (Block)Block.field_149771_c.getObject("vine");
    public static final Block fence_gate = (Block)Block.field_149771_c.getObject("fence_gate");
    public static final Block brick_stairs = (Block)Block.field_149771_c.getObject("brick_stairs");
    public static final Block stone_brick_stairs = (Block)Block.field_149771_c.getObject("stone_brick_stairs");
    public static final BlockMycelium mycelium = (BlockMycelium)Block.field_149771_c.getObject("mycelium");
    public static final Block waterlily = (Block)Block.field_149771_c.getObject("waterlily");
    public static final Block nether_brick = (Block)Block.field_149771_c.getObject("nether_brick");
    public static final Block nether_brick_fence = (Block)Block.field_149771_c.getObject("nether_brick_fence");
    public static final Block nether_brick_stairs = (Block)Block.field_149771_c.getObject("nether_brick_stairs");
    public static final Block nether_wart = (Block)Block.field_149771_c.getObject("nether_wart");
    public static final Block enchanting_table = (Block)Block.field_149771_c.getObject("enchanting_table");
    public static final Block brewing_stand = (Block)Block.field_149771_c.getObject("brewing_stand");
    public static final BlockCauldron cauldron = (BlockCauldron)Block.field_149771_c.getObject("cauldron");
    public static final Block end_portal = (Block)Block.field_149771_c.getObject("end_portal");
    public static final Block end_portal_frame = (Block)Block.field_149771_c.getObject("end_portal_frame");
    public static final Block end_stone = (Block)Block.field_149771_c.getObject("end_stone");
    public static final Block dragon_egg = (Block)Block.field_149771_c.getObject("dragon_egg");
    public static final Block redstone_lamp = (Block)Block.field_149771_c.getObject("redstone_lamp");
    public static final Block lit_redstone_lamp = (Block)Block.field_149771_c.getObject("lit_redstone_lamp");
    public static final BlockSlab double_wooden_slab = (BlockSlab)Block.field_149771_c.getObject("double_wooden_slab");
    public static final BlockSlab wooden_slab = (BlockSlab)Block.field_149771_c.getObject("wooden_slab");
    public static final Block cocoa = (Block)Block.field_149771_c.getObject("cocoa");
    public static final Block sandstone_stairs = (Block)Block.field_149771_c.getObject("sandstone_stairs");
    public static final Block emerald_ore = (Block)Block.field_149771_c.getObject("emerald_ore");
    public static final Block ender_chest = (Block)Block.field_149771_c.getObject("ender_chest");
    public static final BlockTripWireHook tripwire_hook = (BlockTripWireHook)Block.field_149771_c.getObject("tripwire_hook");
    public static final Block tripwire = (Block)Block.field_149771_c.getObject("tripwire");
    public static final Block emerald_block = (Block)Block.field_149771_c.getObject("emerald_block");
    public static final Block spruce_stairs = (Block)Block.field_149771_c.getObject("spruce_stairs");
    public static final Block birch_stairs = (Block)Block.field_149771_c.getObject("birch_stairs");
    public static final Block jungle_stairs = (Block)Block.field_149771_c.getObject("jungle_stairs");
    public static final Block command_block = (Block)Block.field_149771_c.getObject("command_block");
    public static final BlockBeacon beacon = (BlockBeacon)Block.field_149771_c.getObject("beacon");
    public static final Block cobblestone_wall = (Block)Block.field_149771_c.getObject("cobblestone_wall");
    public static final Block flower_pot = (Block)Block.field_149771_c.getObject("flower_pot");
    public static final Block carrots = (Block)Block.field_149771_c.getObject("carrots");
    public static final Block potatoes = (Block)Block.field_149771_c.getObject("potatoes");
    public static final Block wooden_button = (Block)Block.field_149771_c.getObject("wooden_button");
    public static final Block skull = (Block)Block.field_149771_c.getObject("skull");
    public static final Block anvil = (Block)Block.field_149771_c.getObject("anvil");
    public static final Block trapped_chest = (Block)Block.field_149771_c.getObject("trapped_chest");
    public static final Block light_weighted_pressure_plate = (Block)Block.field_149771_c.getObject("light_weighted_pressure_plate");
    public static final Block heavy_weighted_pressure_plate = (Block)Block.field_149771_c.getObject("heavy_weighted_pressure_plate");
    public static final BlockRedstoneComparator unpowered_comparator = (BlockRedstoneComparator)Block.field_149771_c.getObject("unpowered_comparator");
    public static final BlockRedstoneComparator powered_comparator = (BlockRedstoneComparator)Block.field_149771_c.getObject("powered_comparator");
    public static final BlockDaylightDetector daylight_detector = (BlockDaylightDetector)Block.field_149771_c.getObject("daylight_detector");
    public static final Block redstone_block = (Block)Block.field_149771_c.getObject("redstone_block");
    public static final Block quartz_ore = (Block)Block.field_149771_c.getObject("quartz_ore");
    public static final BlockHopper hopper = (BlockHopper)Block.field_149771_c.getObject("hopper");
    public static final Block quartz_block = (Block)Block.field_149771_c.getObject("quartz_block");
    public static final Block quartz_stairs = (Block)Block.field_149771_c.getObject("quartz_stairs");
    public static final Block activator_rail = (Block)Block.field_149771_c.getObject("activator_rail");
    public static final Block dropper = (Block)Block.field_149771_c.getObject("dropper");
    public static final Block stained_hardened_clay = (Block)Block.field_149771_c.getObject("stained_hardened_clay");
    public static final Block hay_block = (Block)Block.field_149771_c.getObject("hay_block");
    public static final Block carpet = (Block)Block.field_149771_c.getObject("carpet");
    public static final Block hardened_clay = (Block)Block.field_149771_c.getObject("hardened_clay");
    public static final Block coal_block = (Block)Block.field_149771_c.getObject("coal_block");
    public static final Block packed_ice = (Block)Block.field_149771_c.getObject("packed_ice");
    public static final Block acacia_stairs = (Block)Block.field_149771_c.getObject("acacia_stairs");
    public static final Block dark_oak_stairs = (Block)Block.field_149771_c.getObject("dark_oak_stairs");
    public static final BlockDoublePlant double_plant = (BlockDoublePlant)Block.field_149771_c.getObject("double_plant");
    public static final BlockStainedGlass stained_glass = (BlockStainedGlass)Block.field_149771_c.getObject("stained_glass");
    public static final BlockStainedGlassPane stained_glass_pane = (BlockStainedGlassPane)Block.field_149771_c.getObject("stained_glass_pane");
    private static final String __OBFID = "CL_00000204";
}