# Controls the launch of the splash screen.
splashscreen = true
# Max threads for parallel loading; -1 uses Runtime#availableProcessors.
maxThreads = -1
# Forge global version checking.
versionCheck = true
