name: 'Pull Request actions'

on:
  pull_request_target:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed, auto_merge_enabled, auto_merge_disabled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  labels:
    uses: MinecraftForge/SharedActions/.github/workflows/pr_actions.yml@main
    secrets:
      GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
      GH_APP_NAME: ${{ secrets.GH_APP_NAME }}