name: 'Pull Request actions'

on: pull_request

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  labels:
    uses: MinecraftForge/SharedActions/.github/workflows/pr_actions.yml@main
    secrets:
      GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
      GH_APP_NAME: ${{ secrets.GH_APP_NAME }}