name: 'PR Review Comment'

on: pull_request_review_comment

jobs:
  upload_payload:
    name: Upload payload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3 # Payload artifact is consumed in Actionable
        with:
          name: payload
          path: ${{ github.event_path }}