name: 'Spam label'

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  discussion:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  discussions: write

jobs:
  lock:
    if: ${{ (github.event.label.name == 'spam') && (github.event.action == 'labeled') }}
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/close-issue@v2
        name: Close Issue
        with: 
          close-reason: 'not_planned'
        if: ${{ github.event_name != 'pull_request' }}
      - run: gh pr close ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Close PR
        if: ${{ github.event_name == 'pull_request' }}
      - uses: maxkomarychev/oction-lock-issue@v0.7.1
        name: Lock PR
        if: ${{ github.event_name == 'pull_request' }}
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          issue_number: ${{ github.event.number }}
      - uses: OSDKDev/lock-issues@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
        name: Lock issue
        if: ${{ github.event_name != 'pull_request' }}
