name: Support Requests

on:
  issues:
    types:
    - labeled
    - unlabeled
    - reopened

permissions:
  issues: write

jobs:
  support:
    runs-on: ubuntu-latest
    steps:
    - uses: dessant/support-requests@v2
      with:
        support-label: Forum
        issue-comment: >
            :wave: We use the issue tracker exclusively for final bug reports and feature requests. 
            However, this issue appears to be better suited for the 
            [Forge Support Forums](https://forums.minecraftforge.net/) or 
            [Forge Discord](https://discord.gg/UvedJ9m). Please create a new topic on the support forum
            with this issue or ask in the `#tech-support` channel in the Discord server, and the 
            conversation can continue there.
        lock-issue: true
